sudo: false
language: scala
jdk: oraclejdk8
scala:
   - 2.11.8
script:
  make -C travis test
addons:
  apt:
    packages:
      - oracle-java8-installer
      - make

cache:
  directories:
    - travis/dependencies
