sudo: false
language: scala
jdk: oraclejdk8
scala:
   - 2.11.8
script:
  make -C travis test
addons:
  apt:
    packages:
      - oracle-java8-installer
      - make

cache:
  directories:
    - travis/dependencies

env:
  - USE_FRAMEBUFFER=false _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
